spring:
  application:
    name: consumer
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
  cloud:
    function:
      definition: consumingFunction
    stream:
      bindings:
        consumingFunction-in-0:
          destination: myDestination
          group: consumingFunctionGroup@${spring.application.name}
          content-type: application/x-protobuf
      default-binder: rabbit
      rabbit:
        bindings:
          consumingFunction-in-0:
            consumer:
              durableSubscription: true
              missingQueuesFatal: true
              maxConcurrency: 1
              batchSize: 1
              prefetch: 1
server:
  port: 0
