spring:
  application:
    name: producer
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
  cloud:
    stream:
      source: createUserEventStream
      bindings:
        createUserEventStream-out-0:
          destination: createUserDestination
          content-type: application/x-protobuf
      default-binder: rabbit
server:
  port: 8001
user:
  host: 127.0.0.1
  port: 8002
