name: CI
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to triggre manual jobs
        required: false
        default: ''
  pull_request:
    branches: [ main, master ]
  push:
env:
  JAVA_VERSION: 1.8
jobs:
  tests:
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: ci
      with:
        path: |
          ~/.npm
          ~/.node
          ~/.local
          ~/.gradle
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - uses: actions/setup-node@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - run: cd $GITHUB_WORKSPACE ; ./mvnw # -B dependency:resolve dependency:resolve-plugins
  integration-tests:
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: ci
      with:
        path: |
          ~/.npm
          ~/.node
          ~/.local
          ~/.gradle
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - uses: actions/setup-node@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - run: cd $GITHUB_WORKSPACE ; ./mvnw -f rabbitmq docker:start
    - run: cd $GITHUB_WORKSPACE ; rm -rf ~/.m2/repository/com/github/daggerok
    - run: cd $GITHUB_WORKSPACE ; ./mvnw install -DskipTests
    - run: cd $GITHUB_WORKSPACE ; ./mvnw -f consumer spring-boot:start # to create durable queue
    - run: cd $GITHUB_WORKSPACE ; ./mvnw -f consumer spring-boot:stop  # to simulate downtime
    - run: cd $GITHUB_WORKSPACE ; ./mvnw -f producer spring-boot:start # and post message in a queue
    - run: cd $GITHUB_WORKSPACE ; curl -sSv 0:8080 -H'Content-Type:application/json' -d'{"message":"Hello, World"}'
    - run: cd $GITHUB_WORKSPACE ; ./mvnw -f consumer spring-boot:start # to restore messages durably
    - run: cd $GITHUB_WORKSPACE ; ./mvnw -f producer spring-boot:stop
    - run: cd $GITHUB_WORKSPACE ; ./mvnw -f consumer spring-boot:stop  # check from logs that message has been received
    - run: cd $GITHUB_WORKSPACE ; ./mvnw -f rabbitmq docker:stop docker:remove
  dependency-updates:
    if: contains(github.event.inputs.trigger, 'M')
      || startsWith(github.event.inputs.trigger, 'm')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - run: |
        echo "Trigger: ${{ github.event.inputs.trigger }}"
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: ci
      with:
        path: |
          ~/.npm
          ~/.node
          ~/.local
          ~/.gradle
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-plugin-updates
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-property-updates
    - run: cd $GITHUB_WORKSPACE ; ./mvnw versions:display-parent-updates
